language: python
python:
 - "2.7"
# command to install dependencies
install: "pip install -r web/requirements.txt"

before_script: "export DJANGO_SETTINGS_MODULE=app.settings"
# command to run tests
script: "python web/manage.py test"
