language: python
python:
 - "2.7"
# command to install dependencies
install:
 - python web/setup.py install
 - pip install -r web/requirements.txt
# command to run tests
script:
 - cd web
 - python manage.py test
